name: Deploy SvelteKit to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PUBLIC_SUPABASE_URL: ${{ secrets.PUBLIC_SUPABASE_URL }}
      PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.PUBLIC_SUPABASE_ANON_KEY }}
      PUBLIC_MAPBOX_TOKEN: ${{ secrets.PUBLIC_MAPBOX_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      # --- IMPORTANT ---
      # Ensure GH Pages finds a SPA fallback at /r-r-dash/404.html.
      # Some SvelteKit versions write index.html at build/r-r-dash/index.html,
      # others at build/index.html. Handle both cases.
      - name: Prepare SPA fallback for Project Pages
        run: |
          set -euxo pipefail
          ls -la build || true
          if [ -f build/404.html ]; then
            FALLBACK_SRC=build/404.html
          elif [ -f build/index.html ]; then
            FALLBACK_SRC=build/index.html
          elif [ -f build/r-r-dash/index.html ]; then
            FALLBACK_SRC=build/r-r-dash/index.html
          else
            echo "Could not find fallback source (404.html or index.html)"; find build -maxdepth 2 -type f; exit 1
          fi
          mkdir -p build/r-r-dash
          cp "$FALLBACK_SRC" build/404.html
          cp "$FALLBACK_SRC" build/r-r-dash/404.html
          echo "Using fallback source: $FALLBACK_SRC"
          echo "---- tree build (top) ----"
          ls -la build
          echo "---- tree build/r-r-dash ----"
          ls -la build/r-r-dash

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
